name: Playwright Python Tests

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest  # You can use macos-latest or windows-latest if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust the Python version as needed

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements file
          pip install pytest-playwright
          playwright install --with-deps  # Install Playwright and dependencies

      - name: Run Playwright tests
        run: pytest --headless --slowmo 100 --html=report.html --self-contained-html

      - name: Upload Playwright test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: report.html
          retention-days: 7
